version: "3.9"

#===============================FRONTEND_CONTAINER
services:
  frontend:
    container_name: front
    build:
      context: front/
    volumes:
      - frontend:/app
    ports:
      - 3000:3000
    env_file: .env
    networks:
      - transcendance
#==============================VOLUMES
volumes:
  frontend:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/front/srcs/app"
#==============================NETWORK
networks:
  transcendance:
    driver: bridge
